token: 09e83850-65ed-4030-b375-51903465a56c
comment: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%
    patch:
      default:
        target: auto
        threshold: 3%

flag_management:
  default_rules:
    carryforward: true
  individual_flags:
    - name: backend
      paths:
        - backend/
    - name: frontend
      paths:
        - frontend/
